apiVersion: v1
kind: Pod
metadata:
  name: cuda-vectoradd
spec:
  restartPolicy: OnFailure
  containers:
  - name: vectoradd
    image: vcr.vngcloud.vn/81-vks-public/samples:vectoradd-cuda11.2.1
    resources:
      limits:
        nvidia.com/gpu: 1                               # Use 1 GPU for this pod
  nodeSelector:
    nvidia.com/gpu.product: <CHANGE-ME>                 # Please make sure compatible with your GPU when using this nodeSelector