apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
name: my-gpu-app
spec:
maxReplicas: 3 # Update this according to your desired number of replicas
minReplicas: 1
scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: time-slicing-verification
metrics:
  - type: Pods
    pods:
      metric:
        name: DCGM_FI_DEV_GPU_UTIL
      target:
        type: AverageValue
        averageValue: 30
  - type: Pods
    pods:
      metric:
        name: DCGM_FI_DEV_MEM_COPY_UTIL
      target:
        type: AverageValue
        averageValue: 30