apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow-mnist
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: tensorflow-mnist
  template:
    metadata:
      labels:
        app: tensorflow-mnist
    spec:
      containers:
      - image: vcr.vngcloud.vn/60108-cuongdm3/tensorflow-mnist-sample:v1.5
        name: tensorflow-mnist
        command:
        - python
        - tensorflow-sample-code/tfjob/docker/mnist/main.py
        - --max_steps=100000
        - --data_dir=tensorflow-sample-code/data
        resources:
          requests:
            nvidia.com/gpu: 1                                              # Request one GPU for the pod
            cpu: 500m
            memory: 1000Mi
          limits:
            cpu: 800m
            memory: 2000Mi
            nvidia.com/gpu: 1                                              # Request one GPU for the pod
        workingDir: /root
      restartPolicy: Always
