apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow-gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorflow-gpu
  template:
    metadata:
      labels:
        app: tensorflow-gpu
    spec:
      containers:
      - name: tensorflow
        image: vcr.vngcloud.vn/60108-cuongdm3/tensorflow:2.16.1-gpu
        command: ["python", "-c", "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([100000, 100000])))"]
        resources:
          limits:
            cpu: 700m
            memory: 1000Mi
            nvidia.com/gpu: 1

