apiVersion: v1
kind: ConfigMap
metadata:
  name: time-slicing-config-fine
data:
  rtx-4090: |-                                  # Same the name with the name that you label the GPU node before
    version: v1
    flags:
      migStrategy: none                         # MIG strategy is not used, this field SHOULD depends on your GPU model
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 10                          # Allow the node using this GPU to be shared by 10 pods
  rtx-2080ti: |-                                # Same the name with the name that you label the GPU node before
    version: v1
    flags:
      migStrategy: none                         # MIG strategy is not used, this field SHOULD depends on your GPU model
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 5                           # Allow the node using this GPU to be shared by 5 pods
  a40: |-                                # Same the name with the name that you label the GPU node before
    version: v1
    flags:
      migStrategy: none                         # MIG strategy is not used, this field SHOULD depends on your GPU model
    sharing:
      mps:
        resources:
        - name: nvidia.com/gpu
          rename: nvidia.com/gpu-4gb
          memoryGB: 4
          replicas: 2
          devices: ["0"]
