apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
    # namespace: annd2
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 30 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
